# Generated by Django 5.1.6 on 2025-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="image_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="image",
            field=models.ImageField(upload_to="uploaded_images/"),
        ),
    ]
