# Generated by Django 5.1.6 on 2025-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_annotation_image_text_alter_annotation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="book_name",
            field=models.TextField(blank=True),
        ),
    ]
