# Generated by Django 5.1.6 on 2025-02-27 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_annotation_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='author_name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='book_name',
            field=models.CharField(blank=True),
        ),
    ]
