# Generated by Django 5.1.6 on 2025-02-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_annotation_annotation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='book_name',
        ),
    ]
