# Generated by Django 5.1.6 on 2025-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_annotation_annotation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='page_number',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
