# Generated by Django 5.1.6 on 2025-03-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_annotation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_annotations',
            field=models.IntegerField(default=0),
        ),
    ]
