# Generated by Django 5.1.6 on 2025-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_book_number_of_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_text',
            field=models.TextField(blank=True),
        ),
    ]
